version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8101:8101"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/xmiipp
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: 975500
      MYSQL_DATABASE: xmiipp
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.6
    command: ["redis-server", "--requirepass", "975500"]
    ports:
      - "6379:6379"

